---
title: "LogisticRegression"
author: "Julian Nieto"
date: "April 8, 2019"
output: html_document
---

```{r}

train_data = read.csv("train.csv")
test_data = read.csv("test.csv")
```



```{r}
library(corrplot)

corr.d <- cor( train_data )
corr.d[ lower.tri( corr.d, diag = TRUE ) ] <- NA
corrplot( corr.d, type = "upper", diag = FALSE )

herosOnly = cbind(train_data$RadiantWin, train_data[, seq(8, 117)])
colnames(herosOnly)[1] = "RadiantWin"

herosOnlyTest = cbind(test_data$RadiantWin, test_data[, seq(8, 117)])

#new_train_data = train_data[, -seq(8, 118)]

mylogit <- glm(`RadiantWin` ~ ., data = herosOnly, family = "binomial")
summary(mylogit)

colnames(herosOnlyTest)[1] = "RadiantWin"

ols <- glm(`RadiantWin` ~ ., data = herosOnlyTest)

log_conf_mat=table(test_data$RadiantWin, as.numeric(predict(mylogit,herosOnlyTest)>=.5))

(log_conf_mat[1,1] + log_conf_mat[2,2])/nrow(test_data)


```



```{r}
# load library
library(neuralnet)

# fit neural network

#herosOnly = cbind(trainData$RadiantWin, trainData[, seq(8, 117)])
#colnames(herosOnly)[1] = "RadiantWin"
#nn=neuralnet(`RadiantWin`~ ., data = herosOnly, hidden= c(100, 200) ,act.fct = "logistic",
nn=neuralnet(`RadiantWin`~ ., data = train_data, hidden= 5,act.fct = "logistic",
                linear.output = FALSE)

plot(nn)
herosOnlyTest = cbind(testData$RadiantWin, testData[, seq(8, 117)])
nn.results <- compute(nn, testData[, seq(8, 117)])
results <- data.frame(actual = testData$RadiantWin, prediction = nn.results$net.result)

roundedresults<-sapply(results,round,digits=0)
roundedresultsdf=data.frame(roundedresults)
attach(roundedresultsdf)
table(actual,prediction)


sum(predict(nn,test_data) > .5)
sum(test_data$RadiantWin)

nn_conf_mat = table(test_data$RadiantWin, as.numeric(predict(nn,test_data)>=.5))

(nn_conf_mat[1,1] + nn_conf_mat[2,2])/nrow(test_data)
```

Neural Network, logistic regresion, and random forest
