---
title: "Project Data"
author: "Will Jeziorski - wsj2"
date: "March 24, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
THE STUFF FOR OBJECTIVES IS 0 INDEXED for PLAYERS
```{r}
library(rjson)
library(utils)
library(tidyr)
```

```{r data_cleaning_step_i}

numberOfBuildings = function(observation) {
  sum(as.integer(intToBits(observation)))
}

# RUN THIS CODE ON EVERY SINGLE JSON DATA FILE. YOU CAN RENAME EACH FILE AT THE VERY END 

fileToDataFrame = function(filename) {
    proj_data = lapply(readLines(filename), fromJSON)
  
    nobs = length(proj_data)
    
    win = rep(0,nobs)
    
    timeschat = rep(0,nobs)
    
    radtower = rep(0,nobs)
    
    diretower = rep(0,nobs)
    
    radracks = rep(0,nobs)
    
    direracks = rep(0,nobs)
    
    racks = 6
    tower = 11
    
    
    for(i in 1:nobs){
      print(i)
      print(proj_data[[i]]$match_id)
      win[i] = proj_data[[i]]$radiant_win
      timeschat[i] = length(proj_data[[i]]$chat)
      radtower[i] = numberOfBuildings(proj_data[[i]]$tower_status_radiant)
      diretower[i] = numberOfBuildings(proj_data[[i]]$tower_status_dire)
      radracks[i] = numberOfBuildings(proj_data[[i]]$barracks_status_radiant)
      direracks[i] = numberOfBuildings(proj_data[[i]]$barracks_status_dire)
    }
    
    which_FB = rep(0,nobs)
    
    for(i in 1:nobs){
      killtime = rep(0,10)
      for(j in 1:10){
        if(length(proj_data[[i]]$players[[j]]$kills_log) == 0){
          killtime[j] = 1E10
          next
        } else {
        killtime[j] = proj_data[[i]]$players[[j]]$kills_log[[1]]$time
        }
      }
      which_FB[i] = which(killtime == min(killtime))[1]
    }
    
    Radiant_FB = as.numeric(which_FB <= 5)
    
    unidata = cbind(win, timeschat, radtower, diretower, radracks, direracks, Radiant_FB)
    
    colnames(unidata) = c("RadiantWin", "TimesChatted", "RadiantTowerStatus", "DireTowerStatus", "RadiantBarracksStatus", "DireBarracksStatus", "RadiantFB")
    
    players = matrix(0,nobs,10)
    
    last_hits = matrix(0,nobs,10)
    
    kills = matrix(0,nobs,10)
    
    deaths = matrix(0,nobs,10)
    
    denies = matrix(0,nobs,10)
    
    damage_taken = matrix(0,nobs,10)
    
    damage_inflicted = matrix(0,nobs,10)
    
    for(i in 1:nobs){
      for (j in 1:10){
        players[i,j] = proj_data[[i]]$players[[j]]$hero_id
        last_hits[i,j] = proj_data[[i]]$players[[j]]$last_hits
        kills[i,j] = proj_data[[i]]$players[[j]]$kills
        deaths[i,j] = proj_data[[i]]$players[[j]]$deaths
        denies[i,j] = proj_data[[i]]$players[[j]]$denies
        if(length(proj_data[[i]]$players[[j]]$damage_taken)== 0){
          damage_taken[i,j] = 0
        } else{
          damage_taken[i,j] = Reduce("+",proj_data[[i]]$players[[j]]$damage_taken)
        }
        if(length(proj_data[[i]]$players[[j]]$damage) == 0){
          damage_inflicted[i,j] = 0
        } else {
          damage_inflicted[i,j] = Reduce("+",proj_data[[i]]$players[[j]]$damage)
        }
      }
    }
    
    heroes = 112
    
    player = matrix(0,nobs,heroes)
    
    for(i in 1:nobs){
      for(j in 1:10){
        for(k in 1:heroes){
          if (players[i,j] !=k){
            next
          } else{
            
          if(j <= 5){
            player[i,k] = (players[i,j] == k)
          } else {
            player[i,k] = -(players[i,j] == k)
          }
          }
          }
        }
        
    }
    
    Hero_ID = rep(0,heroes)
    
    for (i in 1:heroes){
      Hero_ID[i] = paste0("Hero", i)
    }
    
    colnames(player) = Hero_ID
    
    colnames(last_hits) = c("Player1CS", "Player2CS", "Player3CS", "Player4CS", "Player5CS", "Player6CS", "Player7CS", "Player8CS", "Player9CS", "Player10CS")
    
    colnames(kills) = c("Player1Kills", "Player2Kills", "Player3Kills", "Player4Kills", "Player5Kills", "Player6Kills", "Player7Kills", "Player8Kills", "Player9Kills", "Player10Kills")
    
    colnames(deaths) = c("Player1Deaths", "Player2Deaths", "Player3Deaths", "Player4Deaths", "Player5Deaths", "Player6Deaths", "Player7Deaths", "Player8Deaths", "Player9Deaths", "Player10Deaths")
    
    colnames(denies) = c("Player1Denies", "Player2Denies", "Player3Denies", "Player4Denies", "Player5Denies", "Player6Denies", "Player7Denies", "Player8Denies", "Player9Denies", "Player10Denies")
    
    colnames(damage_taken) = c("Player1DamageTaken", "Player2DamageTaken", "Player3DamageTaken", "Player4DamageTaken", "Player5DamageTaken", "Player6DamageTaken", "Player7DamageTaken", "Player8DamageTaken", "Player9DamageTaken", "Player10DamageTaken")
    
    colnames(damage_inflicted) = c("Player1DamageInflicted", "Player2DamageInflicted", "Player3DamageInflicted", "Player4DamageInflicted", "Player5DamageInflicted", "Player6DamageInflicted", "Player7DamageInflicted", "Player8DamageInflicted", "Player9DamageInflicted", "Player10DamageInflicted")
    
    # After finishing up the data initialization, we put all of the data into a data frame.
    
    proj_data_cleaned = as.data.frame(cbind(unidata, player[ , -c(24, 108)], kills, deaths, last_hits, denies, damage_taken, damage_inflicted))
    
    # Reclassification from Numerics to Factors 
    
    
    #proj_data_cleaned$`Radiant Tower Status` = as.factor(proj_data_cleaned$`Radiant Tower Status`)
    
    #proj_data_cleaned$`Dire Tower Status` = as.factor(proj_data_cleaned$`Dire Tower Status`)
    
    #proj_data_cleaned$`Radiant Barracks Status` = as.factor(proj_data_cleaned$`Radiant Barracks Status`)
    
    #proj_data_cleaned$`Dire Barracks Status` = as.factor(proj_data_cleaned$`Dire Barracks Status`)
    return(proj_data_cleaned)
}

```

```{r combining_data_sets, eval = FALSE}
require(stringr)

proj_data_cleaned = fileToDataFrame("new/aa.json")

for (file in list.files(str_c("new"))[-1]) {
  fileStr = paste0("new/", file)
  print("doing")
  print(fileStr)
  proj_data_temp = fileToDataFrame(fileStr)
  print(fileStr)
  print("done")
  proj_data_cleaned = rbind(proj_data_cleaned, proj_data_temp)
  
}

write.csv(proj_data_cleaned,'train.csv')

```

```{r, eval = false}
# THIS IS WHERE IM DEBUGGING SHIT


```
